services:

  app_proxy:
    environment:
      APP_HOST: skybro_web_1
      APP_PORT: 5000

  tracker:
    image: xdeekay/skybro-tracker:1.6.0@sha256:8bc3cfd3abcde2aad340f80e4ea2c67b0883dc14d449263cfe7bd1e021eddaeb
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /etc/localtime:/etc/localtime:ro

  web:
    image: xdeekay/skybro-dashboard:1.6.0@sha256:4f339a81716d1d33b89719b55ee43d7ffb3aac7d0d4f21dcbbb8e88da0294945
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - tracker
