version: "3.9"

services:

  tracker:
    image: xdeekay/skybro-tracker:1.0.0
    container_name: skybro-tracker
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      HOME_LAT: "1.3521"
      HOME_LON: "103.8198"
    networks:
      - skybro-net

  dashboard:
    image: xdeekay/skybro-dashboard:1.0.0
    container_name: skybro-dashboard
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      HOME_LAT: "1.3521"
      HOME_LON: "103.8198"
    depends_on:
      - tracker
    networks:
      - skybro-net

  web:
    image: nginx:alpine
    container_name: skybro-web
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dashboard
    networks:
      - skybro-net

networks:
  skybro-net:
    name: skybro-net
