services:

  app_proxy:
    environment:
      APP_HOST: skybro-web
      APP_PORT: 5000

  tracker:
    image: xdeekay/skybro-tracker:1.0.1
    container_name: skybro-tracker
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      HOME_LAT: "1.3521"
      HOME_LON: "103.8198"
    networks:
      - skybro-net

  web:
    image: xdeekay/skybro-dashboard:1.0.1
    container_name: skybro-web
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      HOME_LAT: "1.3521"
      HOME_LON: "103.8198"
    depends_on:
      - tracker
    networks:
      - default
      - skybro-net

networks:
  default:
    external: true
    name: umbrel_main_network
  skybro-net:
    name: skybro-net
